defaults:
  - optim: sgd
  - dataset: cifar10
  - network: resnet9_equivariant
  - _self_

params:
  aug_mult: 4   # 1 is equal to no augmentations
  decay: 0.999
  bs: 8192
  update_steps: 2160

dp:
  target_epsilon: 8
  target_delta: 1e-5
  clip_norm: 2

# Overwrite from defaults
optim:
  optimizer:
    lr: 2
network:
  layout: [16, 32, 64]
  group: "dihedral"
dataset:
  train_subset: 1.0
  val_subset: 0.0