_target_: networks.EquivariantResNet9
layout: [16, 32, 64]
num_groups: [8, 8, 8]
group: "dihedral"
rotation: 4
restrict: "halved"
fix_params: True
spatial_dims: 32 # update corresponding to dataset image size